# Generated by Django 5.1.3 on 2024-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NongSan', '0002_alter_product_short_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
