"""
Django settings for Nong_San_Sach project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6#-($%%a)o9%t=x6m6y7k(7&9g_1vwc72n4c5pa+3lg)yo730y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    ## đăng nhập và gg, github
    # Allauth apps
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',  # GitHub provider
    'allauth.socialaccount.providers.google',  # Google provider
    'NongSan.apps.NongsanConfig',
    'admin_interface',  # Thêm dòng này
    'colorfield',  # Thêm dòng này để hỗ trợ chỉnh màu
    "import_export",
    "ckeditor",
]
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis broker URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Redis backend URL
CRONJOBS = [
    ('*/5 * * * *', 'NongSan.cron.remove_expired_coupons')
]

AUTH_USER_MODEL = "NongSan.Account"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',  
]

ROOT_URLCONF = "Nong_San_Sach.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# cho gettext()
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

from django.utils.translation import gettext_lazy as _

LANGUAGES = (
    ('en', _('English')),  # Tiếng Anh
    ('vi', _('Vietnamese')),  # Tiếng Việt
)


LANGUAGE_CODE = 'vi'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Social account providers configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
    },
    'github': {
        'APP': {
            'client_id':'0v23li9XfNTaTHr1mXsh',
            'secret':'49c943d788baf9912325b7f536d9b499b9637427',
        }
    }
}

SITE_ID = 1


SOCIALACCOUNT_LOGIN_ON_GET = False
# Redirect URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_AUTO_SIGNUP = True
WSGI_APPLICATION = "Nong_San_Sach.wsgi.application"

# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = "none"  
ACCOUNT_AUTHENTICATION_METHOD = "username"
ACCOUNT_EMAIL_REQUIRED = True


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Xác thực người dùng gg, or github
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend', 
)

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Thư mục để lưu trữ tệp hình ảnh
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SECURE_SSL_REDIRECT = False

# setting for mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'trandinhbien52@gmail.com'  # replace with your email host
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'trandinhbien52@gmail.com'
EMAIL_HOST_PASSWORD = 'trandinhbien522003'

# settings.py

TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Cài đặt múi giờ đúng (Hà Nội)
USE_TZ = True  # Sử dụng múi giờ (True sẽ lưu trữ thời gian UTC trong cơ sở dữ liệu)


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            # Nhóm định dạng cơ bản
            ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'],
            # Heading (1, 2, 3...)
            ['Format'],
            # Kiểu chữ (Font Family, Font Size)
            ['Font', 'FontSize'],
            # Danh sách và căn chỉnh
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            # Liên kết, hình ảnh, bảng, ký tự đặc biệt
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            # Hoàn tác và mã nguồn
            ['Undo', 'Redo', 'Source'],
        ],
        'height': 400,  # Chiều cao CKEditor
        'width': 900,  # Chiều rộng CKEditor
        # Bật các plugin cần thiết
        'extraPlugins': 'format,font,justify',
        # Định nghĩa các lựa chọn kiểu chữ (Font Family)
        'font_names': 'Arial;Times New Roman;Verdana;Comic Sans MS;Courier New',
        # Định nghĩa kích thước chữ (Font Size)
        'fontSize_sizes': '12px;14px;16px;18px;20px;24px;30px;36px',
    },
}
